<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c27647b9-097f-4a31-8e89-2cf6eb9bde10</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.2" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Shared\Shared.Events\Shared.Events.csproj" />
  </ItemGroup>

</Project>
